### ISSUE TITLE
Crash or timeout in /api/srs/mark-correct

### ISSUE THREAD

**Issue by Willem3141** [Willem3141/navi-reykunyu#200]
Reykunyu sometimes crashes when processing `/api/srs/mark-correct`. In the reverse proxy log this shows up as follows:
```
81  2024/12/14 14:45:51 [error] 76564#76564: *228308050 upstream prematurely closed connection while reading response header from upstream, client: [*****], server: reykunyu.lu, request: "POST /api/srs/        ->mark-correct HTTP/2.0", upstream: "http://127.0.0.1:[*****]/api/srs/mark-correct", host: "reykunyu.lu", referrer: "https://reykunyu.lu/study/lesson?c=2&l=1"
```
Afterwards the main Reykunyu process becomes unresponsive (lots of errors in the log) until it auto-restarts. So probably the process crashes or it somehow locks up. However, there is no output at all in Reykunyu's own error log, so it's not trivial to see where it's coming from.

**Comment by Willem3141** [comment]
Adding debug output in `processCorrectAnswer()` seems to indicate that this method completes just fine.

**Comment by Willem3141** [comment]
This may be solved by 403478eecf9f1b137468455fbba45343993bb73a, when that goes into production. (The request validation for `mark-correct` et al. was buggy.)

**Comment by Willem3141** [comment]
```
1   node:internal/errors:464
  1     ErrorCaptureStackTrace(err);
  2     ^
  3 
  4 Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
  5     at new NodeError (node:internal/errors:371:5)
  6     at ServerResponse.removeHeader (node:_http_outgoing:651:11)
  7     at ServerResponse.send (/home/willem3141/Git/navi-reykunyu/node_modules/express/lib/response.js:214:10)
  8     at /home/willem3141/Git/navi-reykunyu/dist/server.js:3758:23
  9     at Statement.<anonymous> (/home/willem3141/Git/navi-reykunyu/dist/server.js:3364:15) {
 10   code: 'ERR_HTTP_HEADERS_SENT'
 11 }
```

**Comment by Willem3141** [comment]
Almost certainly found the cause. [This (unnecessary) sanity check](https://github.com/Willem3141/navi-reykunyu/blob/master/src/zeykerokyu.ts#L357) fails if `vocab === 0`, i.e., if someone is reviewing the word **'angtsìk** :facepalm:
